#!/bin/bash

# Arg validation
die() { echo "$*" 1>&2 ; exit 1; }
[ "$#" -eq 3 ] || die "Usage: /create_simulation.sh frames_per_second length_in_seconds scene_description.txt"

# Execute C code to raytrace individual frames
./Raytrace $@

# Turn frames into .avi simulation video
if [ $? -eq 0 ]; then
 ffmpeg -framerate $1 -i frame%04d.ppm -c:v huffyuv sim.avi
fi

# Delete frames
rm -f *.ppm
